### ISSUE TITLE
error 500 when connection sessions

### ISSUE THREAD

**Issue by AidanFrencken** [nizarfadlan/baileys-api#4]
[02:39:31.890] ERROR (11564): unexpected error in 'init queries'
    err: {
      "type": "Error",
      "message": "bad-request",
      "stack":
          Error: bad-request
              at assertNodeErrorFree (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15)
              at query (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:140:48)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async fetchProps (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:623:28)
              at async Promise.all (index 1)
              at async executeInitQueries (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:709:9)
      "data": 400,
      "isBoom": true,
      "isServer": true,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      }
    }
[02:39:31.920] ERROR (11564): unexpected error in 'init queries'
    err: {
      "type": "Error",
      "message": "bad-request",
      "stack":
          Error: bad-request
              at assertNodeErrorFree (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15)
              at query (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:140:48)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async fetchProps (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:623:28)
              at async Promise.all (index 1)
              at async executeInitQueries (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:709:9)
      "data": 400,
      "isBoom": true,
      "isServer": true,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      }
    }

**Comment by ryanachdiadsyah** [comment]
are you using latest version from this repo ?

**Comment by mdestafadilah** [comment]
> are you using latest version from this repo ?

Yes.
